### ISSUE TITLE
Multiple Buttons in BPopup

### ISSUE THREAD

**Issue by vaibhavsah** [dinbror/bpopup#53]
I am using bpopup to add data in my page. For this I have an add Button in the popup. But on clicking on close/add, same functions are called i.e. bpopup.close(). I want to cancel the submission on close while submission only on Add button

**Comment by dinbror** [comment]
Do you have a live example?

**Comment by vaibhavsah** [comment]
Hey thanks for the reply... But I have solved that issue... Actually Its on
my Client's VPN so can't share it... I will see if I can replicate and
upload. I just called a different method for the button

On Sun, Jun 28, 2015 at 1:19 PM, dinbror notifications@github.com wrote:

> Do you have a live example?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dinbror/bpopup/issues/53#issuecomment-116307528.

## 

Vaibhav  Sah

**Comment by vaibhavsah** [comment]
Vaibhav uses Refind and thinks you should too. Discover, save, and read what's relevant to you.

Accept invite:

https://refind.com/vaibhav__sah?invite=PhYOOyYsO0

Get started through this email, and we'll give you and Vaibhav both 20 coins. At a later point, we'll buy them back with our profits. http://relevance.community

-- 
Refind: https://refind.com


This email was initiated by Vaibhav, not Refind. We may send reminders about this invitation if we don't hear from you.

Unsubscribe: https://refind.com/i/email/unsubscribe/506/invite?address=reply@reply.github.com

**Comment by vaibhavsah** [comment]
Vaibhav uses Refind and thinks you should too. Join Refind to discover, save, and read the most relevant stories on the web.

Accept invite:

https://refind.com/vaibhav__sah?invite=PhYOOyYsO0

-- 
This email was initiated by Vaibhav, not Refind. We may send reminders about this invitation if we don't hear from you.

Unsubscribe: https://refind.com/i/email/unsubscribe/506/invite?address=reply@reply.github.com

**Comment by vaibhavsah** [comment]
A while ago, Vaibhav invited you to Refind, the home for the best stories on the web. When you join via invite, we'll give you and Vaibhav both 20 coins, which we'll repurchase at a later point.

Accept invite:

https://refind.com/vaibhav__sah?invite=PhYOOyYsO0

Learn more:

http://relevance.community

-- 
Unsubscribe: https://refind.com/i/email/unsubscribe/506/invite?address=reply@reply.github.com
