### ISSUE TITLE
Pop-up not centered

### ISSUE THREAD

**Issue by StevenFlecha** [dinbror/bpopup#62]
Hi,

As various other people I have the problem that the popup is not getting centered.
Here is live example: http://rentme.3dprinteroutlet.net/forrent/63/92 

Its not properly centered in any of the latest browsers of Chrome, FF, IE.

Bpopup version 0.11

Thanks!

**Comment by dinbror** [comment]
hey @StevenFlecha .

So it works now after you defined a fixed width?

**Comment by StevenFlecha** [comment]
Hey,
No, its still not centering. 

Note it is centering horizontally, just not vertically. It's to far down. In Chrome its still completely in the screen but in FF for example the bottom is cut off because its too far down:
http://screencast.com/t/tLtrmJKR

B.r.

**Comment by dinbror** [comment]
I can see that you have an iframe with a fixed height in the popup, so if you add a fixed height to the sppopcontent container e.g. 

```
.sppopcontent {
height:436px;
} 
```

then it should work.

**Comment by StevenFlecha** [comment]
That worked, thanks! Been trying setting fixed heights on various places apparently not that one.
Much appreciated.
