### ISSUE TITLE
Horizontal centering with scrollbar

### ISSUE THREAD

**Issue by OxyFuse** [dinbror/bpopup#7]
Horizontal centering works fine if there's no scrollbar. However, if there's a scrollbar, it won't center anymore because it seems that the scrollbar is not included when calculating the window size.

Screenshot:
![bPopup](https://f.cloud.github.com/assets/33974/434638/2a318dd0-af5d-11e2-9e63-526ab86d2ec1.png)

Additional Note:
Works fine in mobile since it's scrollbar is not visible as the desktop browsers.

**Comment by dinbror** [comment]
Fixed in v. 0.11.0
